### ISSUE TITLE
Handle login changes

### ISSUE THREAD

**Issue by AndyClausen** [AndyClausen/yarn-plugin-gcp-auth#1]
If a user wants to switch account, the token is still for the previous account if it hasn't expired in cache yet.

Either add a command to refresh manually or find a way to compare token info to the logged in account without causing delay between each install on private scopes.

**Comment by elderfd** [comment]
Are you open to PRs for this repo? We would like to be able to clear the cache in CI, and I was thinking just to add a command to handle that for now.

**Comment by AndyClausen** [comment]
You'd be very welcome to open a PR, but I actually already made that, just haven't pushed yet. I'll do that now :)

**Comment by AndyClausen** [comment]
v1.2.0 released with a command for refreshing token: `yarn gcp-auth refresh` 🚀

**Comment by AndyClausen** [comment]
Closing this since the command seems sufficient
