### ISSUE TITLE
Using plugin with only a service account fails

### ISSUE THREAD

**Issue by SoftMemes** [AndyClausen/yarn-plugin-gcp-auth#3]
I'm attempting to use this plugin in a CircleCi build to publish npm packages, but have run into some issues.

I have gcloud set up using a service account and `gcloud auth print-access-token` work as expected. However, in this configuration, `gcloud auth application-default print-access-token` prints the following:

```
circleci@88263c19a204:~/project$ gcloud auth application-default print-access-token
WARNING: Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
WARNING: Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
WARNING: Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
ERROR: (gcloud.auth.application-default.print-access-token) Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

It appears that the plugin does not detect this as a failure and later steps result in an invalid access token being used.

**Comment by AndyClausen** [comment]
I must admit, I didn't actually test this case much. I'll take a look at it as soon as I have time, but you're also very welcome to make a PR if you're in a hurry ❤️

**Comment by AndyClausen** [comment]
@SoftMemes Could you test for me if I send you a new version of the plugin? I'm not sure how to reproduce this. I'm on discord as Andy#7956 if you want to have a small debug sesh there.

**Comment by AndyClausen** [comment]
Could you try with the latest version (1.3.2)? I fixed some issues with gcloud there, might've fixed this too.
