### ISSUE TITLE
Feature Request: easy way to ensure ACCESS_TOKEN does not remain on disk after use.

### ISSUE THREAD

**Issue by webervin** [AndyClausen/yarn-plugin-gcp-auth#6]
If during yarn install / yarn focus  ACCESS_TOKEN was provided in the environment,secret value will be stored on disk  in yarn configuration file in user's home directory.  Currently it can be removed if user runs `yarn config set gcpAccessToken --home --json '{}'` or similar command. However information where token is saved/how it is named which is internal knowledge of this plugin, and might change over time. 

Please consider adding some command to logout `yarn gcp-auth logout`, or, if possible do not flush ACCESS_TOKEN to disk at all.

**Comment by AndyClausen** [comment]
I assume this can be closed now?
